// This file is auto-generated by 03_2-md_saver.R
export default [
  { label: 'Rīga', collapsed: true, items: [
    { label: 'Partija "Gods kalpot Rīgai", Zaļo un Zemnieku savienība', slug: 'riga/partija-gods-kalpot-rigai-zalo-un-zemnieku-savieniba' },
    { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'riga/saskana-socialdemokratiska-partija' },
    { label: 'Politiskā partija "Pašcieņa", "Tauta. Zeme. Valstiskums."', slug: 'riga/politiska-partija-pasciena-tauta-zeme-valstiskums' },
    { label: 'Latvijas Sociālistiskā partija', slug: 'riga/latvijas-socialistiska-partija' },
    { label: 'Latvijas Atdzimšanas partija', slug: 'riga/latvijas-atdzimsanas-partija' },
    { label: 'Jaunā VIENOTĪBA', slug: 'riga/jauna-vienotiba' },
    { label: '"Centra Partija"', slug: 'riga/centra-partija' },
    { label: '"PROGRESĪVIE"', slug: 'riga/progresivie' },
    { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'riga/latvija-pirmaja-vieta' },
    { label: '"Latvijas attīstībai"', slug: 'riga/latvijas-attistibai' },
    { label: 'JKP Jaunā konservatīvā partija', slug: 'riga/jkp-jauna-konservativa-partija' },
    { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'riga/suverena-vara-apvieniba-jaunlatviesi' },
    { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'riga/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
    { label: '"APVIENOTAIS SARAKSTS - Latvijas Zaļā partija, Latvijas Reģionu Apvienība, Liepājas partija"', slug: 'riga/apvienotais-saraksts-latvijas-zala-partija-latvijas-regionu-apvieniba-liepajas-partija' },
    { label: '"Platforma 21"', slug: 'riga/platforma-21' },
    { label: 'Politiskā partija "Stabilitātei!"', slug: 'riga/politiska-partija-stabilitatei' }
  ] },
  { label: 'Vidzeme', collapsed: true, items: [
    { label: 'Jūrmala', collapsed: true, items: [
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'vidzeme/jurmala/saskana-socialdemokratiska-partija' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/jurmala/jauna-vienotiba' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/jurmala/latvija-pirmaja-vieta' },
      { label: '"Centra Partija"', slug: 'vidzeme/jurmala/centra-partija' },
      { label: '"Jūrmala-mūsu mājas"', slug: 'vidzeme/jurmala/jurmalamusu-majas' },
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/jurmala/latvijas-zala-partija' },
      { label: '"PROGRESĪVIE"', slug: 'vidzeme/jurmala/progresivie' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/jurmala/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/jurmala/zalo-un-zemnieku-savieniba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/jurmala/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' }
    ] },
    { label: 'Alūksnes novads', collapsed: true, items: [
      { label: 'JKP Jaunā konservatīvā partija', slug: 'vidzeme/aluksnes-novads/jkp-jauna-konservativa-partija' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/aluksnes-novads/latvija-pirmaja-vieta' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/aluksnes-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: '"Latvijas attīstībai"', slug: 'vidzeme/aluksnes-novads/latvijas-attistibai' },
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/aluksnes-novads/latvijas-zala-partija' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/aluksnes-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/aluksnes-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/aluksnes-novads/jauna-vienotiba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/aluksnes-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' }
    ] },
    { label: 'Ādažu novads', collapsed: true, items: [
      { label: '"PROGRESĪVIE"', slug: 'vidzeme/adazu-novads/progresivie' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/adazu-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/adazu-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK", JKP Jaunā konservatīvā partija', slug: 'vidzeme/adazu-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk-jkp-jauna-konservativa-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/adazu-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/adazu-novads/latvija-pirmaja-vieta' },
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/adazu-novads/latvijas-zala-partija' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/adazu-novads/jauna-vienotiba' }
    ] },
    { label: 'Cēsu novads', collapsed: true, items: [
      { label: 'Kustība "Par!"', slug: 'vidzeme/cesu-novads/kustiba-par' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/cesu-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "Pašcieņa"', slug: 'vidzeme/cesu-novads/politiska-partija-pasciena' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/cesu-novads/jauna-vienotiba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/cesu-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"PROGRESĪVIE"', slug: 'vidzeme/cesu-novads/progresivie' },
      { label: 'Zaļo un Zemnieku savienība, "Latvijas attīstībai", VIDZEMES PARTIJA, Latvijas Zaļā partija', slug: 'vidzeme/cesu-novads/zalo-un-zemnieku-savieniba-latvijas-attistibai-vidzemes-partija-latvijas-zala-partija' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/cesu-novads/latvija-pirmaja-vieta' }
    ] },
    { label: 'Gulbenes novads', collapsed: true, items: [
      { label: '"Latvijas attīstībai"', slug: 'vidzeme/gulbenes-novads/latvijas-attistibai' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/gulbenes-novads/jauna-vienotiba' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/gulbenes-novads/latvija-pirmaja-vieta' },
      { label: 'JKP Jaunā konservatīvā partija, VIDZEMES PARTIJA', slug: 'vidzeme/gulbenes-novads/jkp-jauna-konservativa-partija-vidzemes-partija' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/gulbenes-novads/zalo-un-zemnieku-savieniba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/gulbenes-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/gulbenes-novads/politiska-partija-latvijas-regionu-apvieniba' }
    ] },
    { label: 'Ķekavas novads', collapsed: true, items: [
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/kekavas-novads/latvija-pirmaja-vieta' },
      { label: 'VIDZEMES PARTIJA, JKP Jaunā konservatīvā partija', slug: 'vidzeme/kekavas-novads/vidzemes-partija-jkp-jauna-konservativa-partija' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/kekavas-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/kekavas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/kekavas-novads/latvijas-zala-partija' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/kekavas-novads/zalo-un-zemnieku-savieniba' },
      { label: '"Latvijas attīstībai", "POLITISKĀ PARTIJA IZAUGSME"', slug: 'vidzeme/kekavas-novads/latvijas-attistibai-politiska-partija-izaugsme' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/kekavas-novads/jauna-vienotiba' },
      { label: '"SIGULDAS NOVADA PARTIJA"', slug: 'vidzeme/kekavas-novads/siguldas-novada-partija' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/kekavas-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' }
    ] },
    { label: 'Limbažu novads', collapsed: true, items: [
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/limbazu-novads/latvijas-zala-partija' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/limbazu-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/limbazu-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/limbazu-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'VIDZEMES PARTIJA', slug: 'vidzeme/limbazu-novads/vidzemes-partija' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/limbazu-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/limbazu-novads/jauna-vienotiba' }
    ] },
    { label: 'Madonas novads', collapsed: true, items: [
      { label: '"Latvijas attīstībai", "POLITISKĀ PARTIJA IZAUGSME"', slug: 'vidzeme/madonas-novads/latvijas-attistibai-politiska-partija-izaugsme' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/madonas-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/madonas-novads/latvija-pirmaja-vieta' },
      { label: 'JKP Jaunā konservatīvā partija', slug: 'vidzeme/madonas-novads/jkp-jauna-konservativa-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/madonas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Zaļo un Zemnieku savienība, Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/madonas-novads/zalo-un-zemnieku-savieniba-politiska-partija-latvijas-regionu-apvieniba' }
    ] },
    { label: 'Mārupes novads', collapsed: true, items: [
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/marupes-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/marupes-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'JKP Jaunā konservatīvā partija', slug: 'vidzeme/marupes-novads/jkp-jauna-konservativa-partija' },
      { label: '"Latvijas attīstībai"', slug: 'vidzeme/marupes-novads/latvijas-attistibai' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/marupes-novads/latvija-pirmaja-vieta' },
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/marupes-novads/latvijas-zala-partija' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/marupes-novads/jauna-vienotiba' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/marupes-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/marupes-novads/politiska-partija-latvijas-regionu-apvieniba' }
    ] },
    { label: 'Ogres novads', collapsed: true, items: [
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK", Zaļo un Zemnieku savienība, Latvijas Zaļā partija', slug: 'vidzeme/ogres-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk-zalo-un-zemnieku-savieniba-latvijas-zala-partija' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/ogres-novads/jauna-vienotiba' },
      { label: 'VIDZEMES PARTIJA', slug: 'vidzeme/ogres-novads/vidzemes-partija' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'vidzeme/ogres-novads/saskana-socialdemokratiska-partija' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/ogres-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: 'Kustība "Par!", JKP Jaunā konservatīvā partija', slug: 'vidzeme/ogres-novads/kustiba-par-jkp-jauna-konservativa-partija' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/ogres-novads/latvija-pirmaja-vieta' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/ogres-novads/suverena-vara-apvieniba-jaunlatviesi' }
    ] },
    { label: 'Olaines novads', collapsed: true, items: [
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'vidzeme/olaines-novads/saskana-socialdemokratiska-partija' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/olaines-novads/latvija-pirmaja-vieta' },
      { label: 'Latvijas Sociāldemokrātiskā strādnieku partija', slug: 'vidzeme/olaines-novads/latvijas-socialdemokratiska-stradnieku-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/olaines-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: '"Latvijas attīstībai"', slug: 'vidzeme/olaines-novads/latvijas-attistibai' }
    ] },
    { label: 'Ropažu novads', collapsed: true, items: [
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'vidzeme/ropazu-novads/saskana-socialdemokratiska-partija' },
      { label: '"APVIENOTAIS SARAKSTS - Latvijas Zaļā partija, Latvijas Reģionu Apvienība, Liepājas partija"', slug: 'vidzeme/ropazu-novads/apvienotais-saraksts-latvijas-zala-partija-latvijas-regionu-apvieniba-liepajas-partija' },
      { label: '"Latvijas attīstībai", Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/ropazu-novads/latvijas-attistibai-nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"Platforma 21"', slug: 'vidzeme/ropazu-novads/platforma-21' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/ropazu-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Jaunā VIENOTĪBA, "PROGRESĪVIE"', slug: 'vidzeme/ropazu-novads/jauna-vienotiba-progresivie' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/ropazu-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/ropazu-novads/latvija-pirmaja-vieta' }
    ] },
    { label: 'Salaspils novads', collapsed: true, items: [
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK", Zaļo un Zemnieku savienība', slug: 'vidzeme/salaspils-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk-zalo-un-zemnieku-savieniba' },
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/salaspils-novads/latvijas-zala-partija' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/salaspils-novads/latvija-pirmaja-vieta' },
      { label: '"Latvijas Krievu savienība"', slug: 'vidzeme/salaspils-novads/latvijas-krievu-savieniba' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/salaspils-novads/jauna-vienotiba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/salaspils-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/salaspils-novads/politiska-partija-latvijas-regionu-apvieniba' }
    ] },
    { label: 'Saulkrastu novads', collapsed: true, items: [
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/saulkrastu-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/saulkrastu-novads/jauna-vienotiba' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/saulkrastu-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/saulkrastu-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/saulkrastu-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: '"Platforma 21"', slug: 'vidzeme/saulkrastu-novads/platforma-21' }
    ] },
    { label: 'Siguldas novads', collapsed: true, items: [
      { label: '"Latvijas attīstībai"', slug: 'vidzeme/siguldas-novads/latvijas-attistibai' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK", Politiskā partija "Latvijas Reģionu Apvienība", VIDZEMES PARTIJA, JKP Jaunā konservatīvā partija', slug: 'vidzeme/siguldas-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk-politiska-partija-latvijas-regionu-apvieniba-vidzemes-partija-jkp-jauna-konservativa-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/siguldas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/siguldas-novads/jauna-vienotiba' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/siguldas-novads/latvija-pirmaja-vieta' },
      { label: '"LATVIJAS ZEMNIEKU SAVIENĪBA", Latvijas Zaļā partija', slug: 'vidzeme/siguldas-novads/latvijas-zemnieku-savieniba-latvijas-zala-partija' },
      { label: 'Latvijas Atdzimšanas partija', slug: 'vidzeme/siguldas-novads/latvijas-atdzimsanas-partija' },
      { label: '"SIGULDAS NOVADA PARTIJA"', slug: 'vidzeme/siguldas-novads/siguldas-novada-partija' }
    ] },
    { label: 'Smiltenes novads', collapsed: true, items: [
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/smiltenes-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/smiltenes-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Jaunā VIENOTĪBA', slug: 'vidzeme/smiltenes-novads/jauna-vienotiba' },
      { label: '"PROGRESĪVIE"', slug: 'vidzeme/smiltenes-novads/progresivie' },
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/smiltenes-novads/latvijas-zala-partija' },
      { label: 'VIDZEMES PARTIJA', slug: 'vidzeme/smiltenes-novads/vidzemes-partija' }
    ] },
    { label: 'Valkas novads', collapsed: true, items: [
      { label: '"Latvijas attīstībai", "LATVIJAS ZEMNIEKU SAVIENĪBA"', slug: 'vidzeme/valkas-novads/latvijas-attistibai-latvijas-zemnieku-savieniba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/valkas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'VIDZEMES PARTIJA', slug: 'vidzeme/valkas-novads/vidzemes-partija' },
      { label: '"PROGRESĪVIE"', slug: 'vidzeme/valkas-novads/progresivie' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/valkas-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' }
    ] },
    { label: 'Valmieras novads', collapsed: true, items: [
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'vidzeme/valmieras-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'vidzeme/valmieras-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'vidzeme/valmieras-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'vidzeme/valmieras-novads/zalo-un-zemnieku-savieniba' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'vidzeme/valmieras-novads/latvija-pirmaja-vieta' },
      { label: '"Valmierai un Vidzemei"', slug: 'vidzeme/valmieras-novads/valmierai-un-vidzemei' },
      { label: 'Politiskā partija "Pašcieņa"', slug: 'vidzeme/valmieras-novads/politiska-partija-pasciena' },
      { label: 'Latvijas Zaļā partija', slug: 'vidzeme/valmieras-novads/latvijas-zala-partija' }
    ] }
  ] },
  { label: 'Latgale', collapsed: true, items: [
    { label: 'Daugavpils', collapsed: true, items: [
      { label: 'LATVIJA PIRMAJĀ VIETĀ, LATGALES PARTIJA', slug: 'latgale/daugavpils/latvija-pirmaja-vieta-latgales-partija' },
      { label: '"Latvijas attīstībai"', slug: 'latgale/daugavpils/latvijas-attistibai' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/daugavpils/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "KOPĀ LATVIJAI"', slug: 'latgale/daugavpils/politiska-partija-kopa-latvijai' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'latgale/daugavpils/zalo-un-zemnieku-savieniba' },
      { label: '"SARAUJ, LATGALE!"', slug: 'latgale/daugavpils/sarauj-latgale' },
      { label: '"Daugavpils novada partija", Latvijas Zaļā partija', slug: 'latgale/daugavpils/daugavpils-novada-partija-latvijas-zala-partija' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'latgale/daugavpils/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Politiskā partija "Stabilitātei!"', slug: 'latgale/daugavpils/politiska-partija-stabilitatei' },
      { label: '"Daugavpils - mana pils"', slug: 'latgale/daugavpils/daugavpils-mana-pils' }
    ] },
    { label: 'Rēzekne', collapsed: true, items: [
      { label: '"PROGRESĪVIE"', slug: 'latgale/rezekne/progresivie' },
      { label: '"SARAUJ, LATGALE!"', slug: 'latgale/rezekne/sarauj-latgale' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK", Jaunā VIENOTĪBA, "Latvijas attīstībai"', slug: 'latgale/rezekne/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk-jauna-vienotiba-latvijas-attistibai' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'latgale/rezekne/saskana-socialdemokratiska-partija' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ, Politiskā partija "KOPĀ LATVIJAI"', slug: 'latgale/rezekne/latvija-pirmaja-vieta-politiska-partija-kopa-latvijai' },
      { label: 'Latvijas Zaļā partija, Politiskā partija "Latvijas Reģionu Apvienība", JKP Jaunā konservatīvā partija', slug: 'latgale/rezekne/latvijas-zala-partija-politiska-partija-latvijas-regionu-apvieniba-jkp-jauna-konservativa-partija' },
      { label: 'LATGALES PARTIJA', slug: 'latgale/rezekne/latgales-partija' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'latgale/rezekne/zalo-un-zemnieku-savieniba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/rezekne/suverena-vara-apvieniba-jaunlatviesi' },
      { label: '"Latvijas Krievu savienība"', slug: 'latgale/rezekne/latvijas-krievu-savieniba' }
    ] },
    { label: 'Augšdaugavas novads', collapsed: true, items: [
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/augsdaugavas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'LATGALES PARTIJA', slug: 'latgale/augsdaugavas-novads/latgales-partija' },
      { label: '"SARAUJ, LATGALE!"', slug: 'latgale/augsdaugavas-novads/sarauj-latgale' },
      { label: '"LATVIJAS ZEMNIEKU SAVIENĪBA", Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'latgale/augsdaugavas-novads/latvijas-zemnieku-savieniba-nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"Daugavpils novada partija"', slug: 'latgale/augsdaugavas-novads/daugavpils-novada-partija' }
    ] },
    { label: 'Balvu novads', collapsed: true, items: [
      { label: 'Latvijas Zaļā partija', slug: 'latgale/balvu-novads/latvijas-zala-partija' },
      { label: '"Latvijas attīstībai"', slug: 'latgale/balvu-novads/latvijas-attistibai' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'latgale/balvu-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Jaunā VIENOTĪBA', slug: 'latgale/balvu-novads/jauna-vienotiba' },
      { label: 'LATGALES PARTIJA', slug: 'latgale/balvu-novads/latgales-partija' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'latgale/balvu-novads/saskana-socialdemokratiska-partija' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'latgale/balvu-novads/latvija-pirmaja-vieta' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'latgale/balvu-novads/zalo-un-zemnieku-savieniba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/balvu-novads/suverena-vara-apvieniba-jaunlatviesi' }
    ] },
    { label: 'Krāslavas novads', collapsed: true, items: [
      { label: 'Zaļo un Zemnieku savienība', slug: 'latgale/kraslavas-novads/zalo-un-zemnieku-savieniba' },
      { label: '"SARAUJ, LATGALE!"', slug: 'latgale/kraslavas-novads/sarauj-latgale' },
      { label: 'JKP Jaunā konservatīvā partija, "PROGRESĪVIE"', slug: 'latgale/kraslavas-novads/jkp-jauna-konservativa-partija-progresivie' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'latgale/kraslavas-novads/latvija-pirmaja-vieta' },
      { label: '"APVIENOTAIS SARAKSTS - Latvijas Zaļā partija, Latvijas Reģionu Apvienība, Liepājas partija"', slug: 'latgale/kraslavas-novads/apvienotais-saraksts-latvijas-zala-partija-latvijas-regionu-apvieniba-liepajas-partija' },
      { label: 'LATGALES PARTIJA', slug: 'latgale/kraslavas-novads/latgales-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/kraslavas-novads/suverena-vara-apvieniba-jaunlatviesi' }
    ] },
    { label: 'Līvānu novads', collapsed: true, items: [
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'latgale/livanu-novads/latvija-pirmaja-vieta' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'latgale/livanu-novads/saskana-socialdemokratiska-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/livanu-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: '"Latvijas attīstībai", Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK", Jaunā VIENOTĪBA', slug: 'latgale/livanu-novads/latvijas-attistibai-nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk-jauna-vienotiba' },
      { label: 'Latvijas Zaļā partija', slug: 'latgale/livanu-novads/latvijas-zala-partija' },
      { label: 'JKP Jaunā konservatīvā partija', slug: 'latgale/livanu-novads/jkp-jauna-konservativa-partija' },
      { label: '"SARAUJ, LATGALE!"', slug: 'latgale/livanu-novads/sarauj-latgale' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'latgale/livanu-novads/politiska-partija-latvijas-regionu-apvieniba' }
    ] },
    { label: 'Ludzas novads', collapsed: true, items: [
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'latgale/ludzas-novads/latvija-pirmaja-vieta' },
      { label: '"APVIENOTAIS SARAKSTS - Latvijas Zaļā partija, Latvijas Reģionu Apvienība, Liepājas partija"', slug: 'latgale/ludzas-novads/apvienotais-saraksts-latvijas-zala-partija-latvijas-regionu-apvieniba-liepajas-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/ludzas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "KOPĀ LATVIJAI", Latvijas Sociālistiskā partija', slug: 'latgale/ludzas-novads/politiska-partija-kopa-latvijai-latvijas-socialistiska-partija' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'latgale/ludzas-novads/zalo-un-zemnieku-savieniba' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'latgale/ludzas-novads/saskana-socialdemokratiska-partija' },
      { label: 'LATGALES PARTIJA', slug: 'latgale/ludzas-novads/latgales-partija' }
    ] },
    { label: 'Preiļu novads', collapsed: true, items: [
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'latgale/preilu-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'latgale/preilu-novads/latvija-pirmaja-vieta' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība", "PROGRESĪVIE"', slug: 'latgale/preilu-novads/politiska-partija-latvijas-regionu-apvieniba-progresivie' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/preilu-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'LATGALES PARTIJA, Jaunā VIENOTĪBA, "Latvijas attīstībai"', slug: 'latgale/preilu-novads/latgales-partija-jauna-vienotiba-latvijas-attistibai' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'latgale/preilu-novads/zalo-un-zemnieku-savieniba' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'latgale/preilu-novads/saskana-socialdemokratiska-partija' }
    ] },
    { label: 'Rēzeknes novads', collapsed: true, items: [
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'latgale/rezeknes-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"Latvijas attīstībai"', slug: 'latgale/rezeknes-novads/latvijas-attistibai' },
      { label: 'Politiskā partija "KOPĀ LATVIJAI"', slug: 'latgale/rezeknes-novads/politiska-partija-kopa-latvijai' },
      { label: 'Latvijas Zaļā partija', slug: 'latgale/rezeknes-novads/latvijas-zala-partija' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'latgale/rezeknes-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'latgale/rezeknes-novads/latvija-pirmaja-vieta' },
      { label: 'Jaunā VIENOTĪBA, Kustība "Par!", LATGALES PARTIJA, JKP Jaunā konservatīvā partija', slug: 'latgale/rezeknes-novads/jauna-vienotiba-kustiba-par-latgales-partija-jkp-jauna-konservativa-partija' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'latgale/rezeknes-novads/saskana-socialdemokratiska-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'latgale/rezeknes-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'latgale/rezeknes-novads/zalo-un-zemnieku-savieniba' }
    ] }
  ] },
  { label: 'Kurzeme', collapsed: true, items: [
    { label: 'Liepāja', collapsed: true, items: [
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'kurzeme/liepaja/saskana-socialdemokratiska-partija' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'kurzeme/liepaja/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'kurzeme/liepaja/suverena-vara-apvieniba-jaunlatviesi' },
      { label: '"LIEPĀJAS PARTIJA"', slug: 'kurzeme/liepaja/liepajas-partija' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'kurzeme/liepaja/politiska-partija-latvijas-regionu-apvieniba' },
      { label: 'Latvijas Zaļā partija', slug: 'kurzeme/liepaja/latvijas-zala-partija' },
      { label: 'Politiskā partija "Stabilitātei!"', slug: 'kurzeme/liepaja/politiska-partija-stabilitatei' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'kurzeme/liepaja/latvija-pirmaja-vieta' },
      { label: '"Latvijas Krievu savienība"', slug: 'kurzeme/liepaja/latvijas-krievu-savieniba' },
      { label: 'Kustība "Par!"', slug: 'kurzeme/liepaja/kustiba-par' },
      { label: 'Jaunā VIENOTĪBA', slug: 'kurzeme/liepaja/jauna-vienotiba' }
    ] },
    { label: 'Ventspils', collapsed: true, items: [
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'kurzeme/ventspils/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"APVIENOTAIS SARAKSTS - Latvijas Zaļā partija, Latvijas Reģionu Apvienība, Liepājas partija", JKP Jaunā konservatīvā partija', slug: 'kurzeme/ventspils/apvienotais-saraksts-latvijas-zala-partija-latvijas-regionu-apvieniba-liepajas-partija-jkp-jauna-konservativa-partija' },
      { label: '"Latvijai un Ventspilij"', slug: 'kurzeme/ventspils/latvijai-un-ventspilij' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'kurzeme/ventspils/latvija-pirmaja-vieta' },
      { label: 'Kustība "Par!", Jaunā VIENOTĪBA', slug: 'kurzeme/ventspils/kustiba-par-jauna-vienotiba' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'kurzeme/ventspils/saskana-socialdemokratiska-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'kurzeme/ventspils/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "Stabilitātei!"', slug: 'kurzeme/ventspils/politiska-partija-stabilitatei' }
    ] },
    { label: 'Dienvidkurzemes novads', collapsed: true, items: [
      { label: 'Latvijas Zaļā partija', slug: 'kurzeme/dienvidkurzemes-novads/latvijas-zala-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'kurzeme/dienvidkurzemes-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'kurzeme/dienvidkurzemes-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'kurzeme/dienvidkurzemes-novads/latvija-pirmaja-vieta' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'kurzeme/dienvidkurzemes-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Jaunā VIENOTĪBA', slug: 'kurzeme/dienvidkurzemes-novads/jauna-vienotiba' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'kurzeme/dienvidkurzemes-novads/zalo-un-zemnieku-savieniba' }
    ] },
    { label: 'Kuldīgas novads', collapsed: true, items: [
      { label: '"Kuldīgas novadam"', slug: 'kurzeme/kuldigas-novads/kuldigas-novadam' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'kurzeme/kuldigas-novads/latvija-pirmaja-vieta' },
      { label: 'JKP Jaunā konservatīvā partija', slug: 'kurzeme/kuldigas-novads/jkp-jauna-konservativa-partija' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'kurzeme/kuldigas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'kurzeme/kuldigas-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'kurzeme/kuldigas-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Politiskā partija "Republika"', slug: 'kurzeme/kuldigas-novads/politiska-partija-republika' }
    ] },
    { label: 'Saldus novads', collapsed: true, items: [
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'kurzeme/saldus-novads/latvija-pirmaja-vieta' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'kurzeme/saldus-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "Saldus novadam"', slug: 'kurzeme/saldus-novads/politiska-partija-saldus-novadam' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'kurzeme/saldus-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Latvijas Zaļā partija', slug: 'kurzeme/saldus-novads/latvijas-zala-partija' },
      { label: 'Jaunā VIENOTĪBA', slug: 'kurzeme/saldus-novads/jauna-vienotiba' },
      { label: '"Latvijas attīstībai"', slug: 'kurzeme/saldus-novads/latvijas-attistibai' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'kurzeme/saldus-novads/zalo-un-zemnieku-savieniba' }
    ] },
    { label: 'Talsu novads', collapsed: true, items: [
      { label: '"Mēs - Talsiem un novadam"', slug: 'kurzeme/talsu-novads/mes-talsiem-un-novadam' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'kurzeme/talsu-novads/latvija-pirmaja-vieta' },
      { label: 'Latvijas Zaļā partija', slug: 'kurzeme/talsu-novads/latvijas-zala-partija' },
      { label: '"Talsu novada attīstībai", "Latvijas attīstībai"', slug: 'kurzeme/talsu-novads/talsu-novada-attistibai-latvijas-attistibai' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'kurzeme/talsu-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Jaunā VIENOTĪBA', slug: 'kurzeme/talsu-novads/jauna-vienotiba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'kurzeme/talsu-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'kurzeme/talsu-novads/suverena-vara-apvieniba-jaunlatviesi' }
    ] },
    { label: 'Ventspils novads', collapsed: true, items: [
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'kurzeme/ventspils-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'kurzeme/ventspils-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'kurzeme/ventspils-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'kurzeme/ventspils-novads/politiska-partija-latvijas-regionu-apvieniba' }
    ] }
  ] },
  { label: 'Zemgale', collapsed: true, items: [
    { label: 'Jelgava', collapsed: true, items: [
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'zemgale/jelgava/latvija-pirmaja-vieta' },
      { label: '"Centra Partija"', slug: 'zemgale/jelgava/centra-partija' },
      { label: 'Kustība "Par!"', slug: 'zemgale/jelgava/kustiba-par' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'zemgale/jelgava/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Jaunā VIENOTĪBA', slug: 'zemgale/jelgava/jauna-vienotiba' },
      { label: 'JKP Jaunā konservatīvā partija', slug: 'zemgale/jelgava/jkp-jauna-konservativa-partija' },
      { label: 'Latvijas Zaļā partija', slug: 'zemgale/jelgava/latvijas-zala-partija' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'zemgale/jelgava/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'zemgale/jelgava/politiska-partija-latvijas-regionu-apvieniba' },
      { label: '"PROGRESĪVIE"', slug: 'zemgale/jelgava/progresivie' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'zemgale/jelgava/zalo-un-zemnieku-savieniba' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'zemgale/jelgava/saskana-socialdemokratiska-partija' }
    ] },
    { label: 'Aizkraukles novads', collapsed: true, items: [
      { label: 'Zaļo un Zemnieku savienība, Latvijas Zaļā partija', slug: 'zemgale/aizkraukles-novads/zalo-un-zemnieku-savieniba-latvijas-zala-partija' },
      { label: '"Latvijas attīstībai", VIDZEMES PARTIJA', slug: 'zemgale/aizkraukles-novads/latvijas-attistibai-vidzemes-partija' },
      { label: 'Jaunā VIENOTĪBA', slug: 'zemgale/aizkraukles-novads/jauna-vienotiba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'zemgale/aizkraukles-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'zemgale/aizkraukles-novads/latvija-pirmaja-vieta' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'zemgale/aizkraukles-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' }
    ] },
    { label: 'Bauskas novads', collapsed: true, items: [
      { label: '"Latvijas attīstībai"', slug: 'zemgale/bauskas-novads/latvijas-attistibai' },
      { label: '"APVIENOTAIS SARAKSTS - Latvijas Zaļā partija, Latvijas Reģionu Apvienība, Liepājas partija"', slug: 'zemgale/bauskas-novads/apvienotais-saraksts-latvijas-zala-partija-latvijas-regionu-apvieniba-liepajas-partija' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'zemgale/bauskas-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'zemgale/bauskas-novads/zalo-un-zemnieku-savieniba' },
      { label: 'Jaunā VIENOTĪBA', slug: 'zemgale/bauskas-novads/jauna-vienotiba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'zemgale/bauskas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'zemgale/bauskas-novads/latvija-pirmaja-vieta' },
      { label: 'JKP Jaunā konservatīvā partija', slug: 'zemgale/bauskas-novads/jkp-jauna-konservativa-partija' }
    ] },
    { label: 'Dobeles novads', collapsed: true, items: [
      { label: 'Politiskā partija "Republika"', slug: 'zemgale/dobeles-novads/politiska-partija-republika' },
      { label: '"LATVIJAS ZEMNIEKU SAVIENĪBA"', slug: 'zemgale/dobeles-novads/latvijas-zemnieku-savieniba' },
      { label: 'Latvijas Zaļā partija', slug: 'zemgale/dobeles-novads/latvijas-zala-partija' },
      { label: 'Jaunā VIENOTĪBA', slug: 'zemgale/dobeles-novads/jauna-vienotiba' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK", Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'zemgale/dobeles-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk-politiska-partija-latvijas-regionu-apvieniba' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'zemgale/dobeles-novads/suverena-vara-apvieniba-jaunlatviesi' }
    ] },
    { label: 'Jelgavas novads', collapsed: true, items: [
      { label: 'Latvijas Zaļā partija', slug: 'zemgale/jelgavas-novads/latvijas-zala-partija' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'zemgale/jelgavas-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'zemgale/jelgavas-novads/zalo-un-zemnieku-savieniba' },
      { label: '"Latvijas attīstībai"', slug: 'zemgale/jelgavas-novads/latvijas-attistibai' },
      { label: '"Saskaņa" sociāldemokrātiskā partija', slug: 'zemgale/jelgavas-novads/saskana-socialdemokratiska-partija' },
      { label: 'JKP Jaunā konservatīvā partija', slug: 'zemgale/jelgavas-novads/jkp-jauna-konservativa-partija' },
      { label: '"Tauta. Zeme. Valstiskums."', slug: 'zemgale/jelgavas-novads/tauta-zeme-valstiskums' },
      { label: 'Jaunā VIENOTĪBA', slug: 'zemgale/jelgavas-novads/jauna-vienotiba' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'zemgale/jelgavas-novads/latvija-pirmaja-vieta' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'zemgale/jelgavas-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'zemgale/jelgavas-novads/politiska-partija-latvijas-regionu-apvieniba' }
    ] },
    { label: 'Jēkabpils novads', collapsed: true, items: [
      { label: '"Platforma 21"', slug: 'zemgale/jekabpils-novads/platforma-21' },
      { label: 'Politiskā partija "KOPĀ LATVIJAI"', slug: 'zemgale/jekabpils-novads/politiska-partija-kopa-latvijai' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'zemgale/jekabpils-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'Politiskā partija "Republika"', slug: 'zemgale/jekabpils-novads/politiska-partija-republika' },
      { label: 'Latvijas Zaļā partija', slug: 'zemgale/jekabpils-novads/latvijas-zala-partija' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība", JKP Jaunā konservatīvā partija, Partija "VIENOTĪBA"', slug: 'zemgale/jekabpils-novads/politiska-partija-latvijas-regionu-apvieniba-jkp-jauna-konservativa-partija-partija-vienotiba' },
      { label: 'LATGALES PARTIJA', slug: 'zemgale/jekabpils-novads/latgales-partija' },
      { label: '"PROGRESĪVIE"', slug: 'zemgale/jekabpils-novads/progresivie' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'zemgale/jekabpils-novads/latvija-pirmaja-vieta' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'zemgale/jekabpils-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' },
      { label: 'Zaļo un Zemnieku savienība', slug: 'zemgale/jekabpils-novads/zalo-un-zemnieku-savieniba' },
      { label: '"POLITISKĀ PARTIJA IZAUGSME"', slug: 'zemgale/jekabpils-novads/politiska-partija-izaugsme' },
      { label: 'JĒKABPILS REĢIONĀLĀ PARTIJA', slug: 'zemgale/jekabpils-novads/jekabpils-regionala-partija' }
    ] },
    { label: 'Tukuma novads', collapsed: true, items: [
      { label: '"LATVIJAS ZEMNIEKU SAVIENĪBA"', slug: 'zemgale/tukuma-novads/latvijas-zemnieku-savieniba' },
      { label: '"Tukuma pilsētai un novadam"', slug: 'zemgale/tukuma-novads/tukuma-pilsetai-un-novadam' },
      { label: '"SUVERĒNĀ VARA", APVIENĪBA JAUNLATVIEŠI', slug: 'zemgale/tukuma-novads/suverena-vara-apvieniba-jaunlatviesi' },
      { label: 'LATVIJA PIRMAJĀ VIETĀ', slug: 'zemgale/tukuma-novads/latvija-pirmaja-vieta' },
      { label: 'Politiskā partija "Latvijas Reģionu Apvienība"', slug: 'zemgale/tukuma-novads/politiska-partija-latvijas-regionu-apvieniba' },
      { label: 'Latvijas Zaļā partija', slug: 'zemgale/tukuma-novads/latvijas-zala-partija' },
      { label: 'Nacionālā apvienība "Visu Latvijai!"-"Tēvzemei un Brīvībai/LNNK"', slug: 'zemgale/tukuma-novads/nacionala-apvieniba-visu-latvijaitevzemei-un-brivibailnnk' }
    ] }
  ] },
  { label: 'Par projektu', slug: 'par-projektu' }
];
